### ISSUE TITLE
Disable/remove the Age associated with date of Fact/Event

### ISSUE THREAD

**Issue by carlluiz** [fisharebest/webtrees#1063]
How to disable or remove the Age associated with the date of Fact/Event?

**Comment by fisharebest** [comment]
You could hide the age using a custom theme.  You would need CSS such as

```css
#personal_facts_content .age {
  display: none; 
}
```
