### ISSUE TITLE
Investigate auto-growing textarea elements

### ISSUE THREAD

**Issue by fisharebest** [fisharebest/webtrees#4481]
The technique shown at https://codepen.io/chriscoyier/pen/XWKEVLy seems to work well.

Need to get margin/padding/border settings right, to match the bootstrap `form-control` class.

**Comment by fisharebest** [comment]
```css
/* Auto-growing textarea inputs. */
.wt-autogrow-textarea {
    display: grid;
    /* Needs same layout as the textarea */
    padding: 0.375rem 0.75rem; <<<<<< This is not quite right.
}
.wt-autogrow-textarea::after {
    content: attr(data-wt-copy-of-text) " ";
    white-space: pre-wrap;
    visibility: hidden;
}
.wt-autogrow-textarea > textarea {
    resize: none;
    overflow: hidden;
}
.wt-autogrow-textarea > textarea,
.wt-autogrow-textarea::after {
    grid-area: 1 / 1 / 2 / 2;
}
```

```js
  document.querySelectorAll('.wt-autogrow-textarea').forEach(element => {
    const textarea = element.querySelector('textarea');
    element.dataset.wtCopyOfText = textarea.value;
    textarea.addEventListener('input', function (event) {
      element.dataset.wtCopyOfText = event.target.value;
    });
  });
```
