### ISSUE TITLE
Census for Ireland [Request]

### ISSUE THREAD

**Issue by gsmitheidw** [fisharebest/webtrees#4899]
Somewhat related to closed issue #3743 - Ireland seems to be missing from the lists for 1901, 1911 etc.
Technically Ireland was part of the UK until 1922 when the Irish Free State was formed (and eventually in 1937 became named Republic of Ireland), but it also would be a separate entity in line with Scotland and Wales prior to independence anyway.

Could Ireland be added in as a distinct option into the lists of UK censuses?  Irish Censuses are:

- 1821 (Taken over a period from 28 May 1821)
- 1831 (Taken over a period of some months after 30 March 1831)
- 1841 (7 June 1841)
- 1851 (30 March 1851)
- 1901 (31st March 1901)
- 1911 (2 April 1911)

Some notable ones are entirely absent compared to the rest of the UK, largely due to losses in fires during the war of independence.

**Comment by fisharebest** [comment]
Are you able to provide the definitions?

**Comment by gsmitheidw** [comment]
I had a look and couldn't quite figure the structure I'd needed to follow to do a pull request- I'm not much of a coder let alone php. But I'll try and put something together here below. Maybe some sorta structured data format would help? I'll go with yaml:

```yaml
- year: 1821
  date: "After 28 May 1821"
  primary_information:
    - "Surname"
    - "Forename"
    - "Age"
    - "Relation to head of household"
    - "Occupation"
  extended_information:
    - "Not applicable on this census"

- year: 1831
  date: "After 30 March 1831"
  primary_information:
    - "Surname"
    - "Forename, Townland/Street"
    - "House Number"
    - "Barony"
    - "Parish"
    - "County"
  extended_information:
    - "Number of families in each"
    - "Number of males in family"
    - "Number of females in family"
    - "Number of male servants"
    - "Number of female servants"
    - "Number in Established Church"
    - "Number of Roman Catholics"
    - "Number of Presbyterians"
    - "Number of other Protestants"

- year: 1841
  date: "On 7 June 1841"
  primary_information:
    - "Surname"
    - "Forename"
    - "Age in years"
    - "Age in months if under one year"
    - "Sex"
    - "Relation to head"
  extended_information:
    - "Marital Status"
    - "In what year(s) married"
    - "Occupation"
    - "Education"
    - "Native country, county, or city"
    - "Cause of death"
    - "Year of death"

- year: 1851
  date: "On 30 March 1851"
  primary_information:
    - "Surname"
    - "Forename"
    - "Age in years"
    - "Age in months if under one year"
    - "Sex"
    - "Relation to head"
  extended_information:
    - "Marital Status"
    - "In what year(s) married"
    - "Occupation"
    - "Education"
    - "Native country, county, or city"
    - "Cause of death"
    - "Year of death"

- year: 1901
  date: "On 31 March 1901"
  primary_information:
    - "Surname"
    - "Forename"
    - "Age"
    - "Sex"
    - "Relation to head"
    - "Religion"
  extended_information:
    - "Birthplace"
    - "Occupation"
    - "Literacy"
    - "Irish Language"
    - "Marital Status"
    - "Specified Illnesses"

- year: 1911
  date: On 2 April 1911
  primary_information:
    - "Surname"
    - "Forename"
    - "Townland/Street"
    - "DED"
    - "County"
    - "Age"
    - "Sex"
  extended_information:
    - "Birthplace"
    - "Occupation"
    - "Religion"
    - "Literacy"
    - "Irish Language"
    - "Relation to Head of Household"
    - "Marital Status"
    - "Specified Illnesses"
    - "Years Married"
    - "Children Born"
    - "Children Living"

```


## Notes:
The 1841 and 1851 censuses usefully list members of the household not at home on census night, and also family members who died since 1831/1841.


## Sources:
http://www.census.nationalarchives.ie/help/pre1901.html
http://www.census.nationalarchives.ie/help/about19011911census.html
