### ISSUE TITLE
Border spinner while loading

### ISSUE THREAD

**Issue by ekdahl** [fisharebest/webtrees#5044]
Would it be possible to replace the GIF loading symbol from the supplied themes with a border spinner instead?

Bootstrap has a rotating border spinner included which use currentColor as border.
https://getbootstrap.com/docs/5.3/components/spinners/
This would enable easy styling for different color schemes.

I did a small try myself but failed, as the whole content started spinning :).
Maybe it's more work than what is worth, just wanted to raise the idea.

**Comment by fisharebest** [comment]
The spinner is created using the following CSS:

```css
.wt-ajax-load:empty {
    height: 32px;
    width: 32px;
    background: url(images/loading-32x32.gif) no-repeat;
}
```

Google provides several examples of using CSS to create spinners.  I would have thought it was pretty straightforward.
